#!/usr/bin/bash
#
# 1_expressões_regulares_com_grep.sh - Breve descrição
# 
# Site:         https://github.com/SamuelBarbosaDev/
# Autor:        Samuel Barbosa
# Manutenção:   1.1.1
#
#
# ----------------------------------------------------- #
# Aqui você deve utilizar uma descrição mais detalhada
# sobre o seu programa, explicando a forma de utilizar
# 
# Exemplo:
#   $ ./1_expressões_regulares_com_grep.sh -d 1
#   Neste exemplo o script será executado no modo debug
#   nível 1.
# ----------------------------------------------------- #
# Histórico:
#
#   v1.0 18/08/2028, Autor da mudança:
#       - O que mudou?
#   v1.1 19/08//2018, Autor da mudança:
#       - O que mudou:
# ----------------------------------------------------- #
# Agradecimento:
#
#   Samuel - Encontou um bug na parte de login.
#   colaborador 1 - Enviou uma sugestão de adicionar 
#   o -h.

# ------------------------------- VARIÁVEIS ----------------------------------------- #

# ------------------------------------------------------------------------ #

# ------------------------------- TESTES ----------------------------------------- #

# ------------------------------------------------------------------------ #

# ------------------------------- FUNÇÕES ----------------------------------------- #

# ------------------------------------------------------------------------ #

# ------------------------------- EXECUÇÃO ----------------------------------------- #
echo "1-- $(grep "^[a]" /etc/passwd)"
echo "2-- $(grep "[h]$" /etc/passwd)"
echo "3-- $(grep "^r.*h$" /etc/passwd)"
echo "4-- $(grep "^n.*n$" /etc/passwd)"
echo "5-- $(grep "^[a-c]" /etc/passwd)"
echo "6-- $(grep "^r.*h$" /etc/passwd)"
echo "7-- $(grep "^.a" /etc/passwd)"
echo "8-- $(grep "[e-h]$" /etc/passwd)"
echo "9-- $(grep "s.$" /etc/passwd)"
echo "10-- $(egrep "^.{50,}$" /etc/passwd)"

# ------------------------------------------------------------------------ #
